# 사용하기 위해서 addon metrics-server 필요
# kubectl get pods -n kube-system | grep metrics-server
# 서버가 없다면
# minikube start --addons=metrics-server
# minikube addons enable metrics-server

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
